// <auto-generated />
using Chandiman.HttpServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chandiman.HttpServer.Migrations
{
    [DbContext(typeof(WebsiteContext))]
    partial class WebsiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Chandiman.HttpServer.Website", b =>
                {
                    b.Property<string>("WebsiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebsitePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WebsiteId");

                    b.ToTable("Websites");
                });
#pragma warning restore 612, 618
        }
    }
}
